console.log('Общий балл: ', 100);
console.log('Верстка валидная: ', 10);
console.log('Верстка семантическая: ', 20);
console.log(' - <header>, <main>, <footer> ', 2);
console.log(' - шесть элементов <section> (по количеству секций) ', 2);
console.log(' - только один заголовок <h1> ', 2);
console.log(' - пять заголовков <h2> ', 2);
console.log(' - один элемент <nav> ', 2);
console.log(' - два списка ul > li > a (панель навигации, ссылки на соцсети) ', 2);
console.log(' - десять кнопок <button> ', 2);
console.log(' - два инпута: <input type="email"> и <input type="tel"> ', 2);
console.log(' - один элемент <textarea> ', 2);
console.log(' - три атрибута placeholder ', 2);
console.log('Верстка соответствует макету: ', 48);
console.log(' - блок <header> ', 6);
console.log(' - секция hero ', 6);
console.log(' - секция skills ', 6);
console.log(' - секция portfolio ', 6);
console.log(' - секция video ', 6);
console.log(' - секция price ', 6);
console.log(' - секция contacts ', 6);
console.log(' - блок <footer>', 6);
console.log('Требования к CSS: ', 12);
console.log(' - использование флексов или гридов для сетки ', 2);
console.log(' - при уменьшении масштаба верстка по центру, без смещения в сторону ', 2);
console.log(' - фоновый цвет на всю ширину страницы ', 2);
console.log(' - иконки в svg ', 2);
console.log(' - изображения в jpeg ', 2);
console.log(' - favicon ', 2);
console.log('Интерактивность через CSS: ', 20);
console.log(' - плавная прокрутка по якорям ', 5);
console.log(' - ссылки на гитхаб автора и страницу курса ', 5);
console.log(' - hover-эффекты ', 5);
console.log(' - плавность hover-эффектов ', 5);
